name: Manual Git Checkout and Push

on:
  workflow_dispatch:

jobs:
  checkout-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'leangpt'
        git config --global user.email 'noreply@github.com'

    - name: Authenticate with GitHub
      env:
        ACCESS_TOKEN: ${{ secrets.PAT }}
      run: |
        git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/leangpt/leangpt.github.io

    - name: Push to remote repository
      run: |
        git push origin --all